version: "3.9"  # optional since v1.27.0
services:
  web:
    image: nginx:1.21.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/hosts:/etc/nginx/conf.d
      - ./www:/var/www
    links:
      - php
  php:
    image:
      php:8.0-fpm-bullseye
    links:
      - mysql
    volumes:
      - ./www:/var/www
  mysql:
    image:
      mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERL: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: framework.conf
  adminer:
    image:
      adminer:4.8.1
    ports:
      - "8080:8080"
    depends_on:
      - mysql